/**
 * University.Schedule.api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.modelix.sample.restapimodelql

import io.ktor.server.locations.*

object Paths {
    /**
     * Provides access to all known lectures
     *
     */
    @Location("/lectures")
    object getLectures

    /**
     * Provides access to a single lecture
     *
     * @param lectureRef
     */
    @Location("/lectures/{lectureRef}")
    class getLecturesLectureRef(val lectureRef: kotlin.String)

    /**
     * Provides access to all known rooms
     *
     */
    @Location("/rooms")
    object getRooms

    /**
     * Provides access to a single room
     *
     * @param roomRef
     */
    @Location("/rooms/{roomRef}")
    class getRoomsRoomID(val roomRef: kotlin.String)

}
