= Welcome to the modelix samples!
:navtitle: Welcome

  ⚠️ **The examples are currently work in progress** ⚠️

== Introduction

include::samples:partial$short-description.adoc[]

None of the examples try to reuse editors defined in MPS.
If your goal is to reuse MPS editors as is then modelix itself ships with a projector integration to achieve this.

While all the examples use the same language defined in MPS they are not meant as one complete example but rather as individual parts.
The purpose of the examples is to give inspiration of what is possible with modelix and make you think and envision your own use cases.


== Getting Started

include::modelix:ROOT:tutorial/build-component.adoc[leveloffset=+2]

xref:modelix:ROOT:tutorial/build-component.adoc[]

Once the initial build has completes feel free to inspect the xref:samples:usecase.adoc[] and start components as described for each use case.
Alternatively, you can inspect and edit the project with the code editor of your choice.

* The top repository provides `IntelliJ` configurations,
* the xref:mps.adoc[] sub-project can be opened using `MPS 2021.2.6`, and
* the xref:dashboard[] is a `WebStorm` project.

