package org.modelix.model.repositoryconcepts.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import org.modelix.model.repositoryconcepts.structure.JavaModuleFacet;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;

public class JavaModuleFacetConcept extends AbstractConcept<JavaModuleFacet> {

  @NotNull
  @Override
  public JavaModuleFacet createInstance(@NotNull INode node) {
    return new JavaModuleFacet(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final JavaModuleFacetConcept INSTANCE = new JavaModuleFacetConcept();
  private JavaModuleFacetConcept() {
    super(false, "org.modelix.model.repositoryconcepts.structure.JavaModuleFacet", "JavaModuleFacet", "0a7577d1-d4e5-431d-98b1-fae38f9aee80/2206727074858242406");
  }

  @Override
  protected void doInit() {
    this.properties.put("generated", new MPSProperty(this, "generated"));
    this.properties.put("path", new MPSProperty(this, "path"));
    this.superConcepts.add(ModuleFacetConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
