package org.modelix.model.repositoryconcepts.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import org.modelix.model.repositoryconcepts.structure.Model;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.lang.core.structure.concepts.BaseConceptConcept;
import jetbrains.mps.lang.core.structure.concepts.INamedConceptConcept;

public class ModelConcept extends AbstractConcept<Model> {

  @NotNull
  @Override
  public Model createInstance(@NotNull INode node) {
    return new Model(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final ModelConcept INSTANCE = new ModelConcept();
  private ModelConcept() {
    super(false, "org.modelix.model.repositoryconcepts.structure.Model", "Model", "0a7577d1-d4e5-431d-98b1-fae38f9aee80/474657388638618892");
  }

  @Override
  protected void doInit() {
    this.properties.put("id", new MPSProperty(this, "id"));
    this.children.put("rootNodes", new MPSChildLink(this, BaseConceptConcept.INSTANCE, true, true, "rootNodes"));
    this.children.put("modelImports", new MPSChildLink(this, ModelReferenceConcept.INSTANCE, true, true, "modelImports"));
    this.children.put("usedLanguages", new MPSChildLink(this, SingleLanguageDependencyConcept.INSTANCE, true, true, "usedLanguages"));
    this.superConcepts.add(BaseConceptConcept.INSTANCE);
    this.superConcepts.add(INamedConceptConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
