package org.modelix.model.repositoryconcepts.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import org.modelix.model.repositoryconcepts.structure.Module;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.lang.core.structure.concepts.BaseConceptConcept;
import jetbrains.mps.lang.core.structure.concepts.INamedConceptConcept;

public class ModuleConcept extends AbstractConcept<Module> {

  @NotNull
  @Override
  public Module createInstance(@NotNull INode node) {
    return new Module(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final ModuleConcept INSTANCE = new ModuleConcept();
  private ModuleConcept() {
    super(false, "org.modelix.model.repositoryconcepts.structure.Module", "Module", "0a7577d1-d4e5-431d-98b1-fae38f9aee80/474657388638618895");
  }

  @Override
  protected void doInit() {
    this.properties.put("id", new MPSProperty(this, "id"));
    this.properties.put("moduleVersion", new MPSProperty(this, "moduleVersion"));
    this.properties.put("compileInMPS", new MPSProperty(this, "compileInMPS"));
    this.children.put("facets", new MPSChildLink(this, ModuleFacetConcept.INSTANCE, true, true, "facets"));
    this.children.put("models", new MPSChildLink(this, ModelConcept.INSTANCE, true, true, "models"));
    this.children.put("dependencies", new MPSChildLink(this, ModuleDependencyConcept.INSTANCE, true, true, "dependencies"));
    this.children.put("languageDependencies", new MPSChildLink(this, LanguageDependencyConcept.INSTANCE, true, true, "languageDependencies"));
    this.superConcepts.add(BaseConceptConcept.INSTANCE);
    this.superConcepts.add(INamedConceptConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
