package org.modelix.model.repositoryconcepts.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import org.modelix.model.repositoryconcepts.structure.Project;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.lang.core.structure.concepts.BaseConceptConcept;
import jetbrains.mps.lang.core.structure.concepts.INamedConceptConcept;

public class ProjectConcept extends AbstractConcept<Project> {

  @NotNull
  @Override
  public Project createInstance(@NotNull INode node) {
    return new Project(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final ProjectConcept INSTANCE = new ProjectConcept();
  private ProjectConcept() {
    super(false, "org.modelix.model.repositoryconcepts.structure.Project", "Project", "0a7577d1-d4e5-431d-98b1-fae38f9aee80/4008363636171860313");
  }

  @Override
  protected void doInit() {
    this.children.put("modules", new MPSChildLink(this, ModuleConcept.INSTANCE, true, true, "modules"));
    this.children.put("projectModules", new MPSChildLink(this, ProjectModuleConcept.INSTANCE, true, true, "projectModules"));
    this.superConcepts.add(BaseConceptConcept.INSTANCE);
    this.superConcepts.add(INamedConceptConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
