package org.modelix.model.repositoryconcepts.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import org.modelix.model.repositoryconcepts.structure.Repository;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.lang.core.structure.concepts.BaseConceptConcept;

public class RepositoryConcept extends AbstractConcept<Repository> {

  @NotNull
  @Override
  public Repository createInstance(@NotNull INode node) {
    return new Repository(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final RepositoryConcept INSTANCE = new RepositoryConcept();
  private RepositoryConcept() {
    super(false, "org.modelix.model.repositoryconcepts.structure.Repository", "Repository", "0a7577d1-d4e5-431d-98b1-fae38f9aee80/474657388638618902");
  }

  @Override
  protected void doInit() {
    this.children.put("modules", new MPSChildLink(this, ModuleConcept.INSTANCE, true, true, "modules"));
    this.children.put("projects", new MPSChildLink(this, ProjectConcept.INSTANCE, true, true, "projects"));
    this.children.put("tempModules", new MPSChildLink(this, ModuleConcept.INSTANCE, true, true, "tempModules"));
    this.superConcepts.add(BaseConceptConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
