package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.modelix.mps.apigen.runtime.MPSLanguageRegistry;
import org.modelix.mps.apigen.runtime.AbstractConcept;
import java.util.Objects;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3A00000000-0000-4000-0000-011c89590288%28jetbrains.mps.lang.core.structure%29%2F4452961908202556907
 */
public class BaseCommentAttribute extends ChildAttribute implements ISkipConstraintsChecking, IDontApplyTypesystemRules, ISuppressErrors {

  public class Properties extends ChildAttribute.Properties implements INodeHolder, ISkipConstraintsChecking.Properties, IDontApplyTypesystemRules.Properties, ISuppressErrors.Properties {

    @NotNull
    @Override
    public INode getINode() {
      return BaseCommentAttribute.this.getINode();
    }
  }
  public class Children extends ChildAttribute.Children implements INodeHolder, ISkipConstraintsChecking.Children, IDontApplyTypesystemRules.Children, ISuppressErrors.Children {

    @NotNull
    @Override
    public INode getINode() {
      return BaseCommentAttribute.this.getINode();
    }
    @NotNull
    public BaseConcept getCommentedNode() {
      INode child = getINode().getChildren("commentedNode").iterator().next();
      return MPSLanguageRegistry.INSTANCE.getInstance(child);
    }
    public <T extends BaseConcept> T createCommentedNode(AbstractConcept<T> concept) {
      INode newChild;
      if (getINode().getChildren("commentedNode").iterator().hasNext()) {
        throw new IllegalStateException("child already created!");
      } else {
        newChild = getINode().addNewChild("commentedNode", 0, concept);
      }

      return MPSLanguageRegistry.INSTANCE.getInstance(newChild);
    }
    public BaseConcept setCommentedNode(@NotNull BaseConcept value) {
      INode storageNode = getINode();
      INode current = storageNode.getChildren("commentedNode").iterator().next();
      if (Objects.equals(current, value.getINode())) {
        return value;
      }
      storageNode.removeChild(current);
      storageNode.moveChild("commentedNode", 0, value.getINode());
      return value;
    }
  }
  public class References extends ChildAttribute.References implements INodeHolder, ISkipConstraintsChecking.References, IDontApplyTypesystemRules.References, ISuppressErrors.References {

    @NotNull
    @Override
    public INode getINode() {
      return BaseCommentAttribute.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public BaseCommentAttribute(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
