package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractNode;
import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;
import org.modelix.mps.apigen.runtime.AbstractConcept;
import java.util.stream.StreamSupport;
import org.modelix.mps.apigen.runtime.MPSLanguageRegistry;
import java.util.List;
import java.util.stream.Stream;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3A00000000-0000-4000-0000-011c89590288%28jetbrains.mps.lang.core.structure%29%2F1133920641626
 */
public class BaseConcept extends AbstractNode {

  public class Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return BaseConcept.this.getINode();
    }
    @Nullable
    public String getShortDescription() {
      String propertyValue = getINode().getPropertyValue("shortDescription");
      return propertyValue;
    }
    @Nullable
    public String setShortDescription(@Nullable String value) {
      getINode().setPropertyValue("shortDescription", value);
      return value;
    }
    @Nullable
    public String getVirtualPackage() {
      String propertyValue = getINode().getPropertyValue("virtualPackage");
      return propertyValue;
    }
    @Nullable
    public String setVirtualPackage(@Nullable String value) {
      getINode().setPropertyValue("virtualPackage", value);
      return value;
    }
  }
  public class Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return BaseConcept.this.getINode();
    }
    public <T extends Attribute> T createSmodelAttribute(AbstractConcept<T> concept) {
      INode newChild;
      newChild = getINode().addNewChild("smodelAttribute", ((int) StreamSupport.stream(getINode().getChildren("smodelAttribute").spliterator(), false).count()), concept);

      return MPSLanguageRegistry.INSTANCE.getInstance(newChild);
    }
    @NotNull
    public List<? extends Attribute> getSmodelAttribute() {
      Iterable<INode> children = getINode().getChildren("smodelAttribute");
      Stream<INode> stream = StreamSupport.stream(children.spliterator(), false);
      return stream.<Attribute>map(new Function<INode, Attribute>() {
        @Override
        public Attribute apply(INode node) {
          return MPSLanguageRegistry.INSTANCE.getInstance(node);
        }
      }).collect(Collectors.toList());
    }
  }
  public class References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return BaseConcept.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public BaseConcept(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
