package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;

public interface ImplementationPart extends INodeHolder, ScopeFacade {
  interface Properties extends INodeHolder, ScopeFacade.Properties {
  }
  interface Children extends INodeHolder, ScopeFacade.Children {


  }
  interface References extends ScopeFacade.References, INodeHolder {

  }
  Properties getProperties();
  Children getChildren();
}
