package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;

public interface IStubForAnotherConcept extends INodeHolder, InterfacePart {
  interface Properties extends INodeHolder, InterfacePart.Properties {
  }
  interface Children extends INodeHolder, InterfacePart.Children {


  }
  interface References extends InterfacePart.References, INodeHolder {

  }
  Properties getProperties();
  Children getChildren();
}
