package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;

public interface IType extends INodeHolder {
  interface Properties extends INodeHolder {
  }
  interface Children extends INodeHolder {


  }
  interface References extends INodeHolder {

  }
  Properties getProperties();
  Children getChildren();
}
