package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.modelix.mps.apigen.runtime.MPSLanguageRegistry;
import org.modelix.mps.apigen.runtime.AbstractConcept;
import java.util.Objects;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3A00000000-0000-4000-0000-011c89590288%28jetbrains.mps.lang.core.structure%29%2F8703179436978668945
 */
public class MigrationDataAnnotation extends NodeAttribute implements MigrationAnnotation {

  public class Properties extends NodeAttribute.Properties implements INodeHolder, MigrationAnnotation.Properties {

    @NotNull
    @Override
    public INode getINode() {
      return MigrationDataAnnotation.this.getINode();
    }
  }
  public class Children extends NodeAttribute.Children implements INodeHolder, MigrationAnnotation.Children {

    @NotNull
    @Override
    public INode getINode() {
      return MigrationDataAnnotation.this.getINode();
    }
    @NotNull
    public BaseConcept getDataNode() {
      INode child = getINode().getChildren("dataNode").iterator().next();
      return MPSLanguageRegistry.INSTANCE.getInstance(child);
    }
    public <T extends BaseConcept> T createDataNode(AbstractConcept<T> concept) {
      INode newChild;
      if (getINode().getChildren("dataNode").iterator().hasNext()) {
        throw new IllegalStateException("child already created!");
      } else {
        newChild = getINode().addNewChild("dataNode", 0, concept);
      }

      return MPSLanguageRegistry.INSTANCE.getInstance(newChild);
    }
    public BaseConcept setDataNode(@NotNull BaseConcept value) {
      INode storageNode = getINode();
      INode current = storageNode.getChildren("dataNode").iterator().next();
      if (Objects.equals(current, value.getINode())) {
        return value;
      }
      storageNode.removeChild(current);
      storageNode.moveChild("dataNode", 0, value.getINode());
      return value;
    }
  }
  public class References extends NodeAttribute.References implements INodeHolder, MigrationAnnotation.References {

    @NotNull
    @Override
    public INode getINode() {
      return MigrationDataAnnotation.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public MigrationDataAnnotation(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
