package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.Nullable;

public interface MigrationAnnotation extends INodeHolder, MigrationAnnotation_old {
  interface Properties extends INodeHolder, MigrationAnnotation_old.Properties {
    @Nullable
    default String getCreatedByScript() {
      String propertyValue = getINode().getPropertyValue("createdByScript");
      return propertyValue;
    }
    @Nullable
    default String setCreatedByScript(@Nullable String value) {
      getINode().setPropertyValue("createdByScript", value);
      return value;
    }
  }
  interface Children extends INodeHolder, MigrationAnnotation_old.Children {


  }
  interface References extends MigrationAnnotation_old.References, INodeHolder {

  }
  Properties getProperties();
  Children getChildren();
}
