package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3A00000000-0000-4000-0000-011c89590288%28jetbrains.mps.lang.core.structure%29%2F3364660638048049748
 */
public class NodeAttribute extends Attribute {

  public class Properties extends Attribute.Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return NodeAttribute.this.getINode();
    }
  }
  public class Children extends Attribute.Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return NodeAttribute.this.getINode();
    }
  }
  public class References extends Attribute.References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return NodeAttribute.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public NodeAttribute(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
