package jetbrains.mps.lang.core.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3A00000000-0000-4000-0000-011c89590288%28jetbrains.mps.lang.core.structure%29%2F779128492853369165
 */
public class SideTransformInfo extends NodeAttribute {

  public class Properties extends NodeAttribute.Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return SideTransformInfo.this.getINode();
    }
    @Nullable
    public String getSide() {
      String propertyValue = getINode().getPropertyValue("side");
      return propertyValue;
    }
    @Nullable
    public String setSide(@Nullable String value) {
      getINode().setPropertyValue("side", value);
      return value;
    }
    @Nullable
    public String getCellId() {
      String propertyValue = getINode().getPropertyValue("cellId");
      return propertyValue;
    }
    @Nullable
    public String setCellId(@Nullable String value) {
      getINode().setPropertyValue("cellId", value);
      return value;
    }
    @Nullable
    public String getAnchorTag() {
      String propertyValue = getINode().getPropertyValue("anchorTag");
      return propertyValue;
    }
    @Nullable
    public String setAnchorTag(@Nullable String value) {
      getINode().setPropertyValue("anchorTag", value);
      return value;
    }
  }
  public class Children extends NodeAttribute.Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return SideTransformInfo.this.getINode();
    }
  }
  public class References extends NodeAttribute.References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return SideTransformInfo.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public SideTransformInfo(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
