package jetbrains.mps.lang.core.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import jetbrains.mps.lang.core.structure.BaseCommentAttribute;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;

public class BaseCommentAttributeConcept extends AbstractConcept<BaseCommentAttribute> {

  @NotNull
  @Override
  public BaseCommentAttribute createInstance(@NotNull INode node) {
    return new BaseCommentAttribute(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final BaseCommentAttributeConcept INSTANCE = new BaseCommentAttributeConcept();
  private BaseCommentAttributeConcept() {
    super(false, "jetbrains.mps.lang.core.structure.BaseCommentAttribute", "BaseCommentAttribute", "ceab5195-25ea-4f22-9b92-103b95ca8c0c/4452961908202556907");
  }

  @Override
  protected void doInit() {
    this.children.put("commentedNode", new MPSChildLink(this, BaseConceptConcept.INSTANCE, false, false, "commentedNode"));
    this.superConcepts.add(ChildAttributeConcept.INSTANCE);
    this.superConcepts.add(ISkipConstraintsCheckingConcept.INSTANCE);
    this.superConcepts.add(IDontApplyTypesystemRulesConcept.INSTANCE);
    this.superConcepts.add(ISuppressErrorsConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
