package jetbrains.mps.lang.core.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import jetbrains.mps.lang.core.structure.BaseConcept;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;

public class BaseConceptConcept extends AbstractConcept<BaseConcept> {

  @NotNull
  @Override
  public BaseConcept createInstance(@NotNull INode node) {
    return new BaseConcept(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final BaseConceptConcept INSTANCE = new BaseConceptConcept();
  private BaseConceptConcept() {
    super(true, "jetbrains.mps.lang.core.structure.BaseConcept", "BaseConcept", "ceab5195-25ea-4f22-9b92-103b95ca8c0c/1133920641626");
  }

  @Override
  protected void doInit() {
    this.properties.put("shortDescription", new MPSProperty(this, "shortDescription"));
    this.properties.put("virtualPackage", new MPSProperty(this, "virtualPackage"));
    this.children.put("smodelAttribute", new MPSChildLink(this, AttributeConcept.INSTANCE, true, true, "smodelAttribute"));
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
