package jetbrains.mps.lang.core.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import jetbrains.mps.lang.core.structure.PropertyAttribute;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;

public class PropertyAttributeConcept extends AbstractConcept<PropertyAttribute> {

  @NotNull
  @Override
  public PropertyAttribute createInstance(@NotNull INode node) {
    return new PropertyAttribute(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final PropertyAttributeConcept INSTANCE = new PropertyAttributeConcept();
  private PropertyAttributeConcept() {
    super(false, "jetbrains.mps.lang.core.structure.PropertyAttribute", "PropertyAttribute", "ceab5195-25ea-4f22-9b92-103b95ca8c0c/3364660638048049750");
  }

  @Override
  protected void doInit() {
    this.properties.put("name_DebugInfo", new MPSProperty(this, "name_DebugInfo"));
    this.properties.put("propertyId", new MPSProperty(this, "propertyId"));
    this.properties.put("enumUsageMigrated", new MPSProperty(this, "enumUsageMigrated"));
    this.superConcepts.add(AttributeConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
