package jetbrains.mps.lang.core.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import jetbrains.mps.lang.core.structure.ReviewMigration_old;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;

public class ReviewMigration_oldConcept extends AbstractConcept<ReviewMigration_old> {

  @NotNull
  @Override
  public ReviewMigration_old createInstance(@NotNull INode node) {
    return new ReviewMigration_old(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final ReviewMigration_oldConcept INSTANCE = new ReviewMigration_oldConcept();
  private ReviewMigration_oldConcept() {
    super(false, "jetbrains.mps.lang.core.structure.ReviewMigration_old", "ReviewMigration_old", "ceab5195-25ea-4f22-9b92-103b95ca8c0c/2482611074346661065");
  }

  @Override
  protected void doInit() {
    this.properties.put("reasonShort", new MPSProperty(this, "reasonShort"));
    this.properties.put("todo", new MPSProperty(this, "todo"));
    this.properties.put("readableId", new MPSProperty(this, "readableId"));
    this.superConcepts.add(NodeAttributeConcept.INSTANCE);
    this.superConcepts.add(MigrationAnnotation_oldConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
