/**
* University.Schedule.api
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.modelix.sample.restapijsonbulk.models

/**
 * 
 * @param lectureRef 
 * @param name 
 * @param description 
 * @param maxParticipants 
 * @param room 
 */
data class Lecture(
    val lectureRef: kotlin.String,
    val name: kotlin.String,
    val description: kotlin.String,
    val maxParticipants: kotlin.Int,
    val room: kotlin.String
) 

