/**
 * University.Schedule.api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.modelix.sample.restapijsonbulk.models

/**
 *
 * @param roomRef
 * @param name
 * @param maxPlaces
 * @param hasRemoteEquipment
 */
data class Room(
        val roomRef: kotlin.String,
        val name: kotlin.String,
        val maxPlaces: kotlin.Int,
        val hasRemoteEquipment: kotlin.Boolean? = false
) 

