package org.modelix.model.repositoryconcepts.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3Af2f39a18-fd23-4090-b7f2-ba8da340eec2%28org.modelix.model.repositoryconcepts.structure%29%2F2206727074858242406
 */
public class JavaModuleFacet extends ModuleFacet {

  public class Properties extends ModuleFacet.Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return JavaModuleFacet.this.getINode();
    }
    @Nullable
    public Boolean getGenerated() {
      String propertyValue = getINode().getPropertyValue("generated");
      if (propertyValue != null && !(propertyValue.isEmpty())) {
        return Boolean.parseBoolean(propertyValue);
      }
      return null;
    }
    @Nullable
    public Boolean setGenerated(@Nullable Boolean value) {
      if (value != null) {
        getINode().setPropertyValue("generated", Boolean.toString(value));
      } else {
        getINode().setPropertyValue("generated", null);
      }
      return value;
    }
    @Nullable
    public String getPath() {
      String propertyValue = getINode().getPropertyValue("path");
      return propertyValue;
    }
    @Nullable
    public String setPath(@Nullable String value) {
      getINode().setPropertyValue("path", value);
      return value;
    }
  }
  public class Children extends ModuleFacet.Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return JavaModuleFacet.this.getINode();
    }
  }
  public class References extends ModuleFacet.References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return JavaModuleFacet.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public JavaModuleFacet(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
