package org.modelix.model.repositoryconcepts.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;
import org.modelix.mps.apigen.runtime.AbstractConcept;
import java.util.stream.StreamSupport;
import org.modelix.mps.apigen.runtime.MPSLanguageRegistry;
import java.util.List;
import java.util.stream.Stream;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3Af2f39a18-fd23-4090-b7f2-ba8da340eec2%28org.modelix.model.repositoryconcepts.structure%29%2F474657388638618892
 */
public class Model extends BaseConcept implements INamedConcept {

  public class Properties extends BaseConcept.Properties implements INodeHolder, INamedConcept.Properties {

    @NotNull
    @Override
    public INode getINode() {
      return Model.this.getINode();
    }
    @Nullable
    public String getId() {
      String propertyValue = getINode().getPropertyValue("id");
      return propertyValue;
    }
    @Nullable
    public String setId(@Nullable String value) {
      getINode().setPropertyValue("id", value);
      return value;
    }
  }
  public class Children extends BaseConcept.Children implements INodeHolder, INamedConcept.Children {

    @NotNull
    @Override
    public INode getINode() {
      return Model.this.getINode();
    }
    public <T extends BaseConcept> T createRootNodes(AbstractConcept<T> concept) {
      INode newChild;
      newChild = getINode().addNewChild("rootNodes", ((int) StreamSupport.stream(getINode().getChildren("rootNodes").spliterator(), false).count()), concept);

      return MPSLanguageRegistry.INSTANCE.getInstance(newChild);
    }
    public <T extends ModelReference> T createModelImports(AbstractConcept<T> concept) {
      INode newChild;
      newChild = getINode().addNewChild("modelImports", ((int) StreamSupport.stream(getINode().getChildren("modelImports").spliterator(), false).count()), concept);

      return MPSLanguageRegistry.INSTANCE.getInstance(newChild);
    }
    public <T extends SingleLanguageDependency> T createUsedLanguages(AbstractConcept<T> concept) {
      INode newChild;
      newChild = getINode().addNewChild("usedLanguages", ((int) StreamSupport.stream(getINode().getChildren("usedLanguages").spliterator(), false).count()), concept);

      return MPSLanguageRegistry.INSTANCE.getInstance(newChild);
    }
    @NotNull
    public List<? extends BaseConcept> getRootNodes() {
      Iterable<INode> children = getINode().getChildren("rootNodes");
      Stream<INode> stream = StreamSupport.stream(children.spliterator(), false);
      return stream.<BaseConcept>map(new Function<INode, BaseConcept>() {
        @Override
        public BaseConcept apply(INode node) {
          return MPSLanguageRegistry.INSTANCE.getInstance(node);
        }
      }).collect(Collectors.toList());
    }
    @NotNull
    public List<? extends ModelReference> getModelImports() {
      Iterable<INode> children = getINode().getChildren("modelImports");
      Stream<INode> stream = StreamSupport.stream(children.spliterator(), false);
      return stream.<ModelReference>map(new Function<INode, ModelReference>() {
        @Override
        public ModelReference apply(INode node) {
          return MPSLanguageRegistry.INSTANCE.getInstance(node);
        }
      }).collect(Collectors.toList());
    }
    @NotNull
    public List<? extends SingleLanguageDependency> getUsedLanguages() {
      Iterable<INode> children = getINode().getChildren("usedLanguages");
      Stream<INode> stream = StreamSupport.stream(children.spliterator(), false);
      return stream.<SingleLanguageDependency>map(new Function<INode, SingleLanguageDependency>() {
        @Override
        public SingleLanguageDependency apply(INode node) {
          return MPSLanguageRegistry.INSTANCE.getInstance(node);
        }
      }).collect(Collectors.toList());
    }
  }
  public class References extends BaseConcept.References implements INodeHolder, INamedConcept.References {

    @NotNull
    @Override
    public INode getINode() {
      return Model.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public Model(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
