package org.modelix.model.repositoryconcepts.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3Af2f39a18-fd23-4090-b7f2-ba8da340eec2%28org.modelix.model.repositoryconcepts.structure%29%2F4201834143491306084
 */
public class ProjectModule extends ModuleReference {

  public class Properties extends ModuleReference.Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return ProjectModule.this.getINode();
    }
    @Nullable
    public String getVirtualFolder() {
      String propertyValue = getINode().getPropertyValue("virtualFolder");
      return propertyValue;
    }
    @Nullable
    public String setVirtualFolder(@Nullable String value) {
      getINode().setPropertyValue("virtualFolder", value);
      return value;
    }
  }
  public class Children extends ModuleReference.Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return ProjectModule.this.getINode();
    }
  }
  public class References extends ModuleReference.References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return ProjectModule.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public ProjectModule(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
