package org.modelix.model.repositoryconcepts.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3Af2f39a18-fd23-4090-b7f2-ba8da340eec2%28org.modelix.model.repositoryconcepts.structure%29%2F2206727074858242429
 */
public class SingleLanguageDependency extends LanguageDependency {

  public class Properties extends LanguageDependency.Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return SingleLanguageDependency.this.getINode();
    }
    @Nullable
    public Integer getVersion() {
      String propertyValue = getINode().getPropertyValue("version");
      if (propertyValue != null && !(propertyValue.isEmpty())) {
        return Integer.parseInt(propertyValue);
      }
      return null;
    }
    @Nullable
    public Integer setVersion(Integer value) {
      if (value != null) {
        getINode().setPropertyValue("version", Integer.toString(value));
      } else {
        getINode().setPropertyValue("version", null);
      }
      return value;
    }
  }
  public class Children extends LanguageDependency.Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return SingleLanguageDependency.this.getINode();
    }
  }
  public class References extends LanguageDependency.References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return SingleLanguageDependency.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public SingleLanguageDependency(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
