= Use Case 1: Dashboard view
:navtitle: Use Case 1: Dashboard

The imaginary domain use-case is a display next to each room that shows the upcoming lectures in that room.
Additionally, a display in the main hall shows all the lectures of the current day.
This use case envisions a scenario where a system/service outside of MPS wants to consume the content of models defined in MPS (i.e. read only access).


In this simple case, a user does not need to edit these models from the browser.
The xref:dashboard.adoc[], an angular app that serves the content of a model, implements such a simple single page application (SPA).

There are two variations (with sub-variations) of this use case:

A. No automatic update in the SPA: The display refreshes periodically (e.g. every 15 minutes).
B. With automatic updates in the SPA: A display in the main hall would want to show the newest information at all times.

Each variations can further be sub-divided base on the used storage backend.
Wither `MPS` is used to store the model information (e.g. when running an MPS instance in the cloud), or alternatively the modelix `model-server` is used.

NOTE: Depending on the components used, not all features are available.
For example, the `json-bulk-model-access` plugin for MPS is deprecated and does not support writing to the model.

