package University.Schedule.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3Adfa26643-4653-44bc-9dfe-5a6581bcd381%28University.Schedule.structure%29%2F4128798754188010570
 */
public class DateAndTime extends BaseConcept {

  public class Properties extends BaseConcept.Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return DateAndTime.this.getINode();
    }
    @Nullable
    public String getDate() {
      String propertyValue = getINode().getPropertyValue("date");
      return propertyValue;
    }
    @Nullable
    public String setDate(@Nullable String value) {
      getINode().setPropertyValue("date", value);
      return value;
    }
    @Nullable
    public String getTime() {
      String propertyValue = getINode().getPropertyValue("time");
      return propertyValue;
    }
    @Nullable
    public String setTime(@Nullable String value) {
      getINode().setPropertyValue("time", value);
      return value;
    }
  }
  public class Children extends BaseConcept.Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return DateAndTime.this.getINode();
    }
  }
  public class References extends BaseConcept.References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return DateAndTime.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public DateAndTime(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
