package University.Schedule.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;
import org.modelix.mps.apigen.runtime.MPSLanguageRegistry;
import org.modelix.mps.apigen.runtime.AbstractConcept;
import java.util.Objects;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3Adfa26643-4653-44bc-9dfe-5a6581bcd381%28University.Schedule.structure%29%2F4128798754188010560
 */
public class Lecture extends BaseConcept implements INamedConcept {

  public class Properties extends BaseConcept.Properties implements INodeHolder, INamedConcept.Properties {

    @NotNull
    @Override
    public INode getINode() {
      return Lecture.this.getINode();
    }
    @Nullable
    public String getDescription() {
      String propertyValue = getINode().getPropertyValue("description");
      return propertyValue;
    }
    @Nullable
    public String setDescription(@Nullable String value) {
      getINode().setPropertyValue("description", value);
      return value;
    }
    @Nullable
    public Integer getMaxParticipants() {
      String propertyValue = getINode().getPropertyValue("maxParticipants");
      if (propertyValue != null && !(propertyValue.isEmpty())) {
        return Integer.parseInt(propertyValue);
      }
      return null;
    }
    @Nullable
    public Integer setMaxParticipants(Integer value) {
      if (value != null) {
        getINode().setPropertyValue("maxParticipants", Integer.toString(value));
      } else {
        getINode().setPropertyValue("maxParticipants", null);
      }
      return value;
    }
  }
  public class Children extends BaseConcept.Children implements INodeHolder, INamedConcept.Children {

    @NotNull
    @Override
    public INode getINode() {
      return Lecture.this.getINode();
    }
    @NotNull
    public Schedule getSchedule() {
      INode child = getINode().getChildren("schedule").iterator().next();
      return MPSLanguageRegistry.INSTANCE.getInstance(child);
    }
    public <T extends Schedule> T createSchedule(AbstractConcept<T> concept) {
      INode newChild;
      if (getINode().getChildren("schedule").iterator().hasNext()) {
        throw new IllegalStateException("child already created!");
      } else {
        newChild = getINode().addNewChild("schedule", 0, concept);
      }

      return MPSLanguageRegistry.INSTANCE.getInstance(newChild);
    }
    public Schedule setSchedule(@NotNull Schedule value) {
      INode storageNode = getINode();
      INode current = storageNode.getChildren("schedule").iterator().next();
      if (Objects.equals(current, value.getINode())) {
        return value;
      }
      storageNode.removeChild(current);
      storageNode.moveChild("schedule", 0, value.getINode());
      return value;
    }
  }
  public class References extends BaseConcept.References implements INodeHolder, INamedConcept.References {

    @NotNull
    @Override
    public INode getINode() {
      return Lecture.this.getINode();
    }
    @NotNull
    public Room getRoom() {
      return MPSLanguageRegistry.INSTANCE.getInstance(getINode().getReferenceTarget("room"));
    }
    @NotNull
    public Room setRoom(@NotNull Room value) {
      getINode().setReferenceTarget("room", value.getINode());
      return value;
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public Lecture(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
