package University.Schedule.structure;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3Adfa26643-4653-44bc-9dfe-5a6581bcd381%28University.Schedule.structure%29%2F4128798754188010569
 */
public class Recurring extends Schedule {

  public class Properties extends Schedule.Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return Recurring.this.getINode();
    }
  }
  public class Children extends Schedule.Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return Recurring.this.getINode();
    }
  }
  public class References extends Schedule.References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return Recurring.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public Recurring(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
