package University.Schedule.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import org.modelix.mps.apigen.runtime.INodeHolder;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import org.jetbrains.annotations.Nullable;
import org.modelix.mps.apigen.runtime.MPSLanguageRegistry;
import org.modelix.mps.apigen.runtime.AbstractConcept;
import java.util.Objects;

/**
 * Generated for http://127.0.0.1:63320/node?ref=r%3Adfa26643-4653-44bc-9dfe-5a6581bcd381%28University.Schedule.structure%29%2F1648392019017048449
 */
public class Student extends BaseConcept {

  public class Properties extends BaseConcept.Properties implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return Student.this.getINode();
    }
    @Nullable
    public String getName() {
      String propertyValue = getINode().getPropertyValue("name");
      return propertyValue;
    }
    @Nullable
    public String setName(@Nullable String value) {
      getINode().setPropertyValue("name", value);
      return value;
    }
    @Nullable
    public Integer getSemester() {
      String propertyValue = getINode().getPropertyValue("semester");
      if (propertyValue != null && !(propertyValue.isEmpty())) {
        return Integer.parseInt(propertyValue);
      }
      return null;
    }
    @Nullable
    public Integer setSemester(Integer value) {
      if (value != null) {
        getINode().setPropertyValue("semester", Integer.toString(value));
      } else {
        getINode().setPropertyValue("semester", null);
      }
      return value;
    }
  }
  public class Children extends BaseConcept.Children implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return Student.this.getINode();
    }
    @NotNull
    public DateAndTime getBorn() {
      INode child = getINode().getChildren("born").iterator().next();
      return MPSLanguageRegistry.INSTANCE.getInstance(child);
    }
    public <T extends DateAndTime> T createBorn(AbstractConcept<T> concept) {
      INode newChild;
      if (getINode().getChildren("born").iterator().hasNext()) {
        throw new IllegalStateException("child already created!");
      } else {
        newChild = getINode().addNewChild("born", 0, concept);
      }

      return MPSLanguageRegistry.INSTANCE.getInstance(newChild);
    }
    public DateAndTime setBorn(@NotNull DateAndTime value) {
      INode storageNode = getINode();
      INode current = storageNode.getChildren("born").iterator().next();
      if (Objects.equals(current, value.getINode())) {
        return value;
      }
      storageNode.removeChild(current);
      storageNode.moveChild("born", 0, value.getINode());
      return value;
    }
  }
  public class References extends BaseConcept.References implements INodeHolder {

    @NotNull
    @Override
    public INode getINode() {
      return Student.this.getINode();
    }


  }

  private final Properties properties;
  private final Children children;
  private final References references;
  public Student(INode node) {
    super(node);
    this.properties = new Properties();
    this.children = new Children();
    this.references = new References();
  }
  public Properties getProperties() {
    return this.properties;
  }
  public Children getChildren() {
    return this.children;
  }
  public References getReferences() {
    return this.references;
  }
}
