/**
* University.Schedule.api
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.modelix.sample.restapijsonbulk.models.apis

import University.Schedule.structure.Courses
import University.Schedule.structure.Rooms
import com.google.gson.Gson
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.locations.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import jetbrains.mps.lang.core.structure.BaseConcept
import org.modelix.model.api.INode
import org.modelix.model.api.INodeReference
import org.modelix.model.lazy.INodeReferenceSerializer
import org.modelix.mps.apigen.runtime.MPSLanguageRegistry
import org.modelix.sample.restapijsonbulk.Paths
import org.modelix.sample.restapijsonbulk.logger
import org.modelix.sample.restapijsonbulk.models.Lecture
import org.modelix.sample.restapijsonbulk.models.LectureList
import org.modelix.sample.restapijsonbulk.models.Room
import org.modelix.sample.restapijsonbulk.models.RoomList

fun Route.DefaultApi(loadRoots: suspend () -> List<INode>, resolve: suspend (INodeReference) -> INode?) {
    val gson = Gson()
    val empty = mutableMapOf<String, Any?>()

    get<Paths.getLectures> {
        val roots = loadRoots()
        val allLectures = roots.flatMap {
            (it.allChildren.map { MPSLanguageRegistry.getInstance<BaseConcept>(it) })
        }.filterIsInstance<Courses>()
                .flatMap { it.children.lectures }

        val roomList = LectureList(lectures = allLectures.map {
            Lecture(name = it.properties.name ?: "",
                    description = it.properties.description ?: "",
                    lectureRef = INodeReferenceSerializer.serialize(it.iNode.reference),
                    room = INodeReferenceSerializer.serialize(it.references.room.iNode.reference),
                    maxParticipants = it.properties.maxParticipants ?: 0)
        })
        call.respond(roomList)
    }

    get<Paths.getLecturesLectureRef> {
        try {
            val lectureRef = INodeReferenceSerializer.deserialize(call.parameters["lectureRef"]!!.decodeURLPart())
            val iNode = resolve(lectureRef)!!
            val instance = MPSLanguageRegistry.getInstance<University.Schedule.structure.Lecture>(iNode)!!
            val lecture = Lecture(name = instance.properties.name!!,
                    maxParticipants = instance.properties.maxParticipants!!,
                    lectureRef = INodeReferenceSerializer.serialize(instance.iNode.reference),
                    room = INodeReferenceSerializer.serialize(instance.references.room.reference),
                    description = instance.properties.description!!
            )
            call.respond(lecture)
        } catch (e: RuntimeException) {
            call.respond(HttpStatusCode.NotFound, "Can not load Room: " + e.message)
            return@get
        }
    }

    get<Paths.getRooms> {
        val roots = loadRoots()
        val allRooms = roots.flatMap { (it.allChildren.map { MPSLanguageRegistry.getInstance<BaseConcept>(it) }) }
                .filterIsInstance<Rooms>()
                .flatMap { it.children.rooms }

        allRooms.forEach { logger.info("room: " + it.iNode + " " + it.iNode.reference.toString()) }


        val roomList = RoomList(rooms = allRooms.map {
            Room(
                    name = it.properties.name ?: "",
                    maxPlaces = it.properties.maxPlaces ?: 0,
                    roomRef = INodeReferenceSerializer.serialize(it.iNode.reference),
                    hasRemoteEquipment = it.properties.hasRemoteEquipment)
        })
        call.respond(roomList)
    }


    get<Paths.getRoomsRoomID> {
        try {
            val roomRef = INodeReferenceSerializer.deserialize(call.parameters["roomRef"]!!.decodeURLPart())
            val iNode = resolve(roomRef)!!
            val instance = MPSLanguageRegistry.getInstance<University.Schedule.structure.Room>(iNode)!!
            val room = Room(name = instance.properties.name!!,
                    roomRef = INodeReferenceSerializer.serialize(instance.iNode.reference),
                    maxPlaces = instance.properties.maxPlaces!!,
                    hasRemoteEquipment = instance.properties.hasRemoteEquipment
            )
            call.respond(room)
        } catch (e: RuntimeException) {
            call.respond(HttpStatusCode.NotFound, "Can not load Room: " + e.message)
            return@get
        }
    }

}
