= Intermediate OpenAPI of the Courses domain
:navtitle: Intermediate OpenAPI


This component of a single `openapi.yml` file which provides the OpenAPI specification of the REST API implementations serving as examples in this project.
The described API provides an additional domain-specific abstraction of the courses domainfootnote:[This additional abstraction admittedly does not really provide fancy abstractions for this domain.
Its purpose is rather educational for you to understand the option to add an additional layer separating web development from language engineering.
You do not have to do this.
Of course one does not necessarily need such an abstraction layer - any dashboard or web app can directly communicate with the API provided by the `model-server` together with the xref:samples:reference/meta-model-model-api.adoc[generated model API]].

The intention of this abstraction is to provide an example on how the use of `modelix` can be abstracted for eventual consumer apps, such as the xref:samples:reference/dashboard.adoc[Angular based dashboard].
The development process thus can follow a https://swagger.io/resources/articles/adopting-an-api-first-approach/[API-first approach].
Consequently, this openAPI provides a contract of the API behaviour for web teams and a language engineers.

There are currently three implementations of this OpenAPI specification:

1. xref:samples:reference/rest-api-json-bulk.adoc[] (deprecated)
2. xref:samples:reference/rest-api-model-server.adoc[]
3. xref:samples:reference/rest-api-model-ql.adoc[]

