package University.Schedule.structure.concepts;

/*Generated by MPS */

import org.modelix.mps.apigen.runtime.AbstractConcept;
import University.Schedule.structure.LectureAssignments;
import org.jetbrains.annotations.NotNull;
import org.modelix.model.api.INode;
import java.util.HashMap;
import org.modelix.mps.apigen.runtime.MPSProperty;
import org.modelix.mps.apigen.runtime.MPSChildLink;
import org.modelix.mps.apigen.runtime.MPSReferenceLink;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.lang.core.structure.concepts.BaseConceptConcept;

public class LectureAssignmentsConcept extends AbstractConcept<LectureAssignments> {

  @NotNull
  @Override
  public LectureAssignments createInstance(@NotNull INode node) {
    return new LectureAssignments(node);
  }
  private final HashMap<String, MPSProperty> properties = new HashMap<String, MPSProperty>();
  private final HashMap<String, MPSChildLink> children = new HashMap<String, MPSChildLink>();
  private final HashMap<String, MPSReferenceLink> references = new HashMap<String, MPSReferenceLink>();
  private final List<AbstractConcept<?>> superConcepts = new ArrayList<AbstractConcept<?>>();
  public static final LectureAssignmentsConcept INSTANCE = new LectureAssignmentsConcept();
  private LectureAssignmentsConcept() {
    super(false, "University.Schedule.structure.LectureAssignments", "LectureAssignments", "96533389-8d4c-46f2-b150-8d89155f7fca/1648392019017048460");
  }

  @Override
  protected void doInit() {
    this.children.put("lectures", new MPSChildLink(this, AssignmentConcept.INSTANCE, true, true, "lectures"));
    this.references.put("", new MPSReferenceLink(this, StudentConcept.INSTANCE, false, "student"));
    this.superConcepts.add(BaseConceptConcept.INSTANCE);
  }
  @NotNull
  @Override
  protected HashMap<String, MPSProperty> myProperties() {
    return properties;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSChildLink> myChildLinks() {
    return children;
  }
  @NotNull
  @Override
  protected HashMap<String, MPSReferenceLink> myReferenceLinks() {
    return references;
  }
  @NotNull
  @Override
  protected List<AbstractConcept<?>> mySuperConcepts() {
    return superConcepts;
  }
}
